version: '3.8'

services:
  init-db:
    build: ./
    command: python init_db.py
    environment:
      - DB_HOST=db
      - DB_USER=postgre
      - DB_PASSWORD=1111
      - DB_NAME=visitsdb
    depends_on:
      - db
    restart: "no"

  app:
    build: ./
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=1111
      - DB_NAME=visitsdb
    depends_on:
      init-db:
        condition: service_completed_successfully
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    volumes:
      - db_:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  db_:
